---
name: Build disk image
on:
  workflow_dispatch:

env:
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  DEFAULT_TAG: "latest"

jobs:
  build_release:

    name: Build and release disk image

    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: read
      id-token: write

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Mount BTRFS for podman storage
        id: container-storage-action
        uses: ublue-os/container-storage-action@911baca08baf30c8654933e9e9723cb399892140
        continue-on-error: true
        with:
          target-dir: /var/lib/containers
          mount-opts: compress-force=zstd:2

      - name: Build ISO
        id: build-iso
        uses: osbuild/bootc-image-builder-action@main
        with:
          builder-image: ghcr.io/zena-linux/bootc-image-builder:latest
          config-file: ./iso/${{ env.IMAGE_NAME }}.toml
          image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DEFAULT_TAG }}
          types: anaconda-iso
          rootfs: btrfs
          additional-args: --use-librepo=True

      - name: Upload Artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v5
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ steps.build-iso.outputs.output-directory }}
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true
