name: build-image-chunka

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      #
      # checkout repo
      #
      - name: Checkout
        uses: actions/checkout@v6

      #
      # install podman/buildah
      #
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman buildah skopeo

      #
      # install chunkah
      #
      - name: Install chunkah
        run: |
          cargo install chunkah

      #
      # login to ghcr
      #
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            podman login ghcr.io \
              -u "${{ github.actor }}" \
              --password-stdin

      #
      # build container image from Containerfile
      #
      - name: Build image
        run: |
          podman build \
            --tag $IMAGE_NAME:$IMAGE_TAG \
            -f Containerfile .

      #
      # rechunk image
      #
      - name: Rechunk image
        run: |
          sudo chunkah build \
            --from $IMAGE_NAME:$IMAGE_TAG \
            --tag $IMAGE_NAME:${IMAGE_TAG}-chunked

      #
      # push chunked image
      #
      - name: Push image
        run: |
          podman push \
            $IMAGE_NAME:${IMAGE_TAG}-chunked
