name: Build, rechunk, and push image
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Build, rechunk, and push the image
        uses: jharmison-redhat/action-bootc-build@v1
        with:
          push: "true"
          tag: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
