name: build-image-chunka

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}
  IMAGE_TAG: latest
  tag: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      #
      # checkout repo
      #
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build image
        run: |
          podman build -t ${{ env.tag }} .
      
      - name: Rechunk image
        run: |
          mkdir -p chunkah
      
          sudo podman run --rm --privileged \
            -v /var/lib/containers:/var/lib/containers \
            -v $PWD/chunkah:/output \
            quay.io/coreos/chunkah:latest \
            build \
            --local \
            ${{ env.tag }}
      
      - name: Push image
        run: |
          podman push \
            --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            ${{ env.tag }}
